version: '3.2'
services:

  order-service:
    image: paspaola/order-service:0.0.1
    ports:
      - 8090:8090
    depends_on:
      - mongodb
      - kafkabroker
    networks:
      - mcpaspao

  kitchen-service:
    image: paspaola/kitchen-service:0.0.1
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafkabroker
    networks:
      - mcpaspao

  delivery-service:
    image: paspaola/delivery-service:0.0.1
    ports:
      - 8070:8070
    depends_on:
      - mongodb
      - kafkabroker
    networks:
      - mcpaspao

  mongodb:
    image: mongo:3.4.22-xenial
    ports:
      - 27017:27017
    networks:
      - mcpaspao

  kafkabroker:
    image: paspaola/kafka-mcpaspao
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTNERS=192.168.91.121
    networks:
      - mcpaspao

networks:
  mcpaspao:
